swagger: '2.0'
info:
  description: Mfe file manager RESTful interface.
  version: 1.0.12
  title: MfeFileMgr API
basePath: /
schemes:
  - http
  - https
paths:
  '/file/{provider}/{endpoint}/{bucket}':
    get:
      tags:
        - File
      summary: Get all files in a bucket
      description: Get all files in a bucket
      produces:
        - application/json
      operationId: getAllFilesInBucket
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          description: "对应于aliyun的'endpoint'，对应于qiniu的'zone'"
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/MfeFile'
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/MfeFileMgrErrorInfo'
    delete:
      tags:
        - File
      summary: Delete a batch of files in a bucket
      description: Delete a batch of files in a bucket
      produces:
      - application/json
      operationId: deleteFiles
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: keys
          in: body
          description: key list for files to be deleted.
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: successful operation
        '404':
          description: Bucket not found
        '500':
          description: Internal Error (key list for  files which were failed to delete.)
          schema:
            type: array
            items:
              type: string
  '/file/{provider}/{endpoint}/{bucket}/{key}':
    get:
      tags:
        - File
      summary: Get one file in a bucket
      description: Get one file in a bucket
      produces:
        - application/json
      operationId: getFile
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: key
          in: path
          description: file key
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MfeFile'
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/MfeFileMgrErrorInfo'
    delete:
      tags:
        - File
      summary: Delete one file in a bucket
      description: Delete one file in a bucket
      produces:
        - application/json
      operationId: deleteFile
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: key
          in: path
          description: file key
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/MfeFileMgrErrorInfo'
  '/file/{provider}/{endpoint}/{bucket}/prefix/{prefix}':
    get:
      tags:
        - File
      summary: Get all files which key start with prefix in a bucket
      description: Get all files which key start with prefix in a bucket
      produces:
        - application/json
      operationId: getAllFilesStartWithPrefix
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: prefix
          in: path
          description: prefix
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/MfeFile'
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/MfeFileMgrErrorInfo'
    delete:
      tags:
        - File
      summary: Delete all files which key start with prefix in a bucket
      description: Delete all files which key start with prefix in a bucket
      produces:
        - application/json
      operationId: deleteAllFilesStartWithPrefix
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: prefix
          in: path
          description: prefix
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '404':
          description: Bucket not found
        '500':
          description: Internal Error (key list for  files which were failed to delete.)
          schema:
            type: array
            items:
              type: string


  '/dir/{provider}/{endpoint}/{bucket}':
    get:
      tags:
        - Directory
      summary: List all files and sub directories in root directory (one level)
      description: List all files and sub directories in root directory (one level)
      produces:
        - application/json
      operationId: listRootDir
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MfeDirInfo'
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/MfeFileMgrErrorInfo'
  '/dir/{provider}/{endpoint}/{bucket}/{directory}':
    get:
      tags:
        - Directory
      summary: List all files and sub directories in a directory (one level)
      description: List all files and sub directories in a directory (one level)
      produces:
        - application/json
      operationId: listDir
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: directory
          in: path
          description: "directory: have to be '<dir>/[<dir>/]..."
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MfeDirInfo'
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/MfeFileMgrErrorInfo'
    delete:
      tags:
        - Directory
      summary: Delete a directory (all sub tree)
      description: Delete a directory (all sub tree)
      produces:
        - application/json
      operationId: deleteDir
      parameters:
        - name: provider
          in: path
          required: true
          description: is not case sensitive.
          schema:
            $ref: '#/definitions/Provider'
        - name: endpoint
          in: path
          required: true
          type: string
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: directory
          in: path
          description: "directory: have to be '<dir>/[<dir>/]..."
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/MfeDirInfo'
        '404':
          description: Bucket not found
        '500':
          description: Internal Error (key list for  files which were failed to delete.)
          schema:
            type: array
            items:
              type: string
definitions:
  MfeFile:
    type: object
    description: Mfefile model
    properties:
      key:
        type: string
        description: 'key'
      fsize:
        type: integer
        format: int64
        description: 'file size in bytes'
      mimeType:
        type: string
      putTime:
        type: integer
        format: int64
      endUser:
        type: string
      hash:
        type: string

  MfeDirInfo:
    type: object
    description: "directory info: including files and sub dirs."
    properties:
      files:
        type: array
        description: files in this directory.
        items:
          $ref: '#/definitions/MfeFile'
      subdirs:
        type: array
        description: subdirs in this directory.
        items:
          type: string
  Provider:
    description: is not case sensitive.
    type: string
    enum:
      - MFEFILEMGR
      - QINIU
      - ALIYUN
      - AWS

  MfeFileMgrErrorInfo:
    type: object
    properties:
      provider:
        $ref: "#/definitions/Provider"
      code:
        type: integer
      message:
        type: string
        example: File %s creation error
          