swagger: '2.0'
info:
  description: MFE QNMGR RESTful interface.
  version: 1.0.12
  title: Qnmgr API
basePath: /
schemes:
  - http
  - https
paths:
  '/files/{zone}/{bucket}':
    get:
      tags:
        - Files
      summary: Get all files in a bucket
      description: Get all files in a bucket
      produces:
        - application/json
      operationId: getAllFiles
      parameters:
        - name: zone
          in: path
          description: "华东:zone0, 华北:zone1, 华南:zone2, 北美:zoneNa0"
          required: true
          type: string
          enum:
            - zone0
            - zone1
            - zone2
            - zoneNa0
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/QnFile'
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/QnmgrErrorInfo'
    delete:
      tags:
        - Files
      summary: Delete files in a bucket
      description: Delete files in a bucket
      produces:
      - application/json
      operationId: deleteFiles
      parameters:
        - name: zone
          in: path
          description: "华东:zone0, 华北:zone1, 华南:zone2, 北美:zoneNa0"
          required: true
          type: string
          enum:
            - zone0
            - zone1
            - zone2
            - zoneNa0
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: keys
          in: body
          description: key list for files to be deleted.
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: successful operation
        '404':
          description: Bucket not found
        '500':
          description: Internal Error (key list for  files which were failed to delete.)
          schema:
            type: array
            items:
              type: string

  '/files/{zone}/{bucket}/{directory}':
    get:
      tags:
        - Files
      summary: List all files and sub directories in a directory (one level)
      description: List all files and sub directories in a directory (one level)
      produces:
        - application/json
      operationId: listDir
      parameters:
        - name: zone
          in: path
          description: "华东:zone0, 华北:zone1, 华南:zone2, 北美:zoneNa0"
          required: true
          type: string
          enum:
            - zone0
            - zone1
            - zone2
            - zoneNa0
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: directory
          in: path
          description: "directory: have to be '<dir>/[<dir>/]..."
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/QnDirInfo'
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/QnmgrErrorInfo'
  '/files/{zone}/{bucket}/{key}':
    delete:
      tags:
        - Files
      summary: Delete on file in a bucket
      description: Delete on file in a bucket
      produces:
      - application/json
      operationId: deleteFile
      parameters:
        - name: zone
          in: path
          description: "华东:zone0, 华北:zone1, 华南:zone2, 北美:zoneNa0"
          required: true
          type: string
          enum:
            - zone0
            - zone1
            - zone2
            - zoneNa0
        - name: bucket
          in: path
          description: bucket name
          required: true
          type: string
        - name: key
          in: path
          description: key for file to be deleted.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '404':
          description: Bucket not found
        '500':
          description: Internal Error
          schema:
            $ref: '#/definitions/QnmgrErrorInfo'

definitions:
  QnFile:
    type: object
    description: the qn FileInfo model
    properties:
      key:
        type: string
        description: 'key'
      fsize:
        type: integer
        format: int64
        description: 'file size in bytes'
      mimeType:
        type: string
      putTime:
        type: integer
        format: int64
      endUser:
        type: string
      hash:
        type: string

  QnDirInfo:
    type: object
    description: "directory info: including files and sub dirs."
    properties:
      files:
        type: array
        description: files in this directory.
        items:
          $ref: '#/definitions/QnFile'
      subdirs:
        type: array
        description: subdirs in this directory.
        items:
          type: string

  QnmgrErrorInfo:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
        example: File %s creation error
          