package com.mfe.qnmgr.exception;

public enum QnMgrExceptionType {
    EXCPT_NOT_IMPLEMENTED, EXCPT_INTERNAL_ERROR, EXCPT_INVALID_INPUT, EXCPT_OBJECT_IN_USE, EXCPT_TP_INVALID_ENDPOINT, EXCPT_ENTITY_NOT_FOUND, EXCPT_TIMESLOT_IN_USE, EXCPT_PROTECTION_EFFORT_NOT_MET, EXCPT_NOT_IN_VALID_STATE, EXCPT_UNABLE_TO_COMPLY, EXCPT_NE_COMM_LOSS, EXCPT_CAPACITY_EXCEEDED, EXCPT_ACCESS_DENIED, EXCPT_TOO_MANY_OPEN_ITERATORS, EXCPT_UNSUPPORTED_ROUTING_CONSTRAINTS, EXCPT_USERLABEL_IN_USE, EXCPT_DB_CONN_LOSS, EXCPT_SQL_EXEC_ERROR, EXCPT_IO_ERROR, EXCPT_CONF_NOT_FOUND, EXCPT_CONVERT_ERROR, EXCPT_OTHER_ERROR
}
